### ISSUE TITLE
Errgroup version?

### ISSUE THREAD

**Issue by StevenACoffman** [heartwilltell/waitabit#1]
Hello! I was really impressed by the developer ergonomics of your great library, but I wanted to get more familiar with errgroup, so I made an errgroup version of your library called [grace](https://github.com/StevenACoffman/grace) which you might be interested in. I'd definitely appreciate any feedback, as you appear to have excellent taste!

**Comment by heartwilltell** [comment]
Thanks. I really appreciate your feedback. As soon as I return to laptop I will definitely take a look at your work.
